{% set name = "spyx" %}
{% set version = "0.1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spyx-{{ version }}.tar.gz
  sha256: c72044312c93f47978ae5af50465ad964536027f70917ccbab1550f5380e6cca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dm-haiku
    - optax
    - jax-tqdm
    - nir

test:
  imports:
    - spyx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kmheckel/spyx
  summary: 'Spyx: SNNs in JAX'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
