{% set name = "spyx" %}
{% set version = "0.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spyx-{{ version }}.tar.gz
  sha256: 55a8b01d36419ec4420d8a01fb1caf346c0c06505829ba783f031b6b911d43bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dm-haiku
    - optax
    - jax-tqdm
    - nir

test:
  imports:
    - spyx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kmheckel/spyx
  summary: 'Spyx: SNNs in JAX'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
